# install all packages inside /deps/ with pacman
mkdir /deps -p
buildDependencies=$(find /deps/ -type f -name "*.pkg.tar.zst")
pacman -Sy
if [ -n "$buildDependencies" ]; then
	pacman -U --needed --noconfirm $buildDependencies
fi
if ! command -v sudo >/dev/null 2>&1; then
	pacman -S --needed --noconfirm sudo
fi
if ! id builduser >/dev/null 2>&1; then
	useradd builduser -m
	passwd -d builduser
fi
if ! grep -q '^builduser ALL=(ALL) ALL$' /etc/sudoers; then
	printf 'builduser ALL=(ALL) ALL\nDefaults    env_keep += "PKGDEST"\nDefaults    env_keep += "BUILDDIR"\nDefaults    env_keep += "CARGO_HOME"\nDefaults    env_keep += "PACMAN"\n' >> /etc/sudoers
fi

# Some PKGBUILDs misbehave and write build outputs into the PKGBUILD folder.
# To avoid dirtying the bind-mounted `/src` (and causing rebuild loops), build from a private copy.
mkdir -p /work/src
cp -a /src/. /work/src/
chown builduser:builduser /work/src -R
cd /work/src

export CARGO_HOME=/out/cargo-home
mkdir -p "$CARGO_HOME"
if [ -n "${ARDOS_CARGO_OVERRIDES:-}" ]; then
	{
		printf '# Generated by Ardos Packer from package.cargo_workspaces.\n'
		current_source=
		printf '%s\n' "$ARDOS_CARGO_OVERRIDES" | while IFS= read -r override; do
			[ -n "$override" ] || continue
			source=${override%%|*}
			package_override=${override#*|}
			name=${package_override%%=*}
			path=${package_override#*=}
			if [ "$source" != "$current_source" ]; then
				if [ "$source" = crates-io ]; then
					printf '\n[patch.crates-io]\n'
				else
					printf '\n[patch."%s"]\n' "$source"
				fi
				current_source=$source
			fi
			printf '"%s" = { path = "%s" }\n' "$name" "$path"
		done
	} > "$CARGO_HOME/config.toml"
else
	rm -f "$CARGO_HOME/config.toml"
fi
mkdir /out/makepkg -p
chown builduser:builduser /out/ -R

sudo -u builduser bash -c 'makepkg --noconfirm --noprogressbar -s -f'
